openapi: "3.0.0"
info:
  title: Greeting Service
  version: 1.0.0
paths:
  /sayHello:
    get:
      summary: Greet a person
      description: Greet a person by name
      tags:
        - greeting
      parameters:
        - name: name
          in: query
          description: Name of the person to greet
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetResponseModel'
      deprecated: false
      security: []
components:
  schemas:
    GreetResponseModel:
      description: Greet response
      properties:
        message:
          type: string
      type: object